name: space_gpt
description: "A space-themed chat application with Gemini Pro integration"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  bloc:
  flutter_bloc:
  dio:
  lottie: ^3.1.3
  cupertino_icons: ^1.0.8
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/bot_profiles/
    - assets/user_profiles/


  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/SpaceMono-Bold.ttf
